# Generated by Django 5.1.6 on 2025-03-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
